</main>


<footer>
  <div class="partFooter">
    <img src="img/gaming-pc.png"alt="">
  </div>
  <div class="partFooter">
    <h4>Servicios</h4>
    <a href="#">LINK</a>
    <a href="#">LINK</a>
    <a href="#">LINK</a>
    <a href="#">LINK</a>
  </div>
  <div class="partFooter">
    <h4>Acerca De:</h4>
    <a href="#">About us</a>
    <a href="#">About us</a>
    <a href="#">About us</a>
  </div>
  <div class="partFooter">
    <h4>Redes Sociales</h4>
    <div class="social-media">
      <i class="fa-brands fa-facebook"></i>
      <i class="fa-brands fa-twitter"></i>
      <i class="fa-brands fa-tiktok"></i>
      <i class="fa-brands fa-github"></i>
    </div>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
  AOS.init();
</script>

</body>

</html>