<!DOCTYPE html>
<html lang="en">

<!-- head -->

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Gaming SHOP es tu mejor opcion para adquirir tu PC Gamer o perifericos">
    <meta name="keywords" content="Gamer, computadora, perifericos, monitor, silla gamer, pc armadas">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@217;400&display=swap');
    </style>
    <link rel="icon" href="img/gaming-pc.png">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://kit.fontawesome.com/ec81e88ab5.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="estilos/style.css">
    <title>Gaming Shop</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav>
            <div class="marcas">

                <div class="navMarcas">

                    <img src="img/nav_amd.png" alt="" width="40px">
                    <img src="img/nav_geforce.png" alt="" width="40px">
                    <img src="img/nav_intel.png" alt="" width="40px">
                    <img src="img/nav_logitech.png" alt="" width="40px">

                </div>

            </div>

            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="home"><img src="img/gaming-pc.png" alt="" width="50rem"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="productos">Productos</a>
                            </li>
                            <?php if (!isset($_SESSION['USER_ID'])) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="login">Login</a>
                                </li>
                            <?php else : ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
                                </li>
                            <?php endif ?>
                            <li class="nav-item">
                                <a class="nav-link" href="registro">Registrarme</a>
                            </li>
                        </ul>
                        <span class="navbar-text">
                            Carrito
                        </span>
                    </div>
                </div>
            </nav>

        </nav>
    </header>

    <main>