<?php require 'tempaltes/header.phtml'; ?>


<section class="mainHome">

    <section class="mainFotos">


        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="img/Project Stealth-1653278497.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>--GamingSHOP--</h5>
                        <p>Pagina mas grande de Argentina en venta de productos</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="img/Radeon RX 6X50 Series-1652262975.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <p>25% OFF en Productos</p>
                        <h5><a href="index2.html" id="link1">Ver Productos</a></h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="img/fondo10.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>--GamingSHOP--</h5>
                        <p>Unite a la membresia para obtener descuentos</p>
                        <h5><a href="" id="link1">MEMBRESIA</a></h5>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>


    </section>

    <section class="mainInfo">

        <h1 data-aos="fade-up">--Gaming<span>SHOP</span>--</h1>

        <p data-aos="fade-down">GamingSHOP es una empresa líder en tarjetas madre, tarjetas gráficas, laptops, hardware de juegos y sistemas de alto rendimiento. ¡Nos apasiona unirnos a los jugadores para desafiar los límites sin miedo y luchar mientras nos elevamos a la gloria máxima!</p>

        <h1 data-aos="fade-up">EXPLORA Gaming<span>SHOP</span></h1>

        <p data-aos="fade-down">Descubre inspiración para compilaciones de PC, consejos de bricolaje, trucos de juegos, eventos de en todo el mundo y más.</p>

    </section>

    <section class="results">
            <div class="contenedor content-results">
                <section class="numbers">
                    <div class="number" data-aos="zoom-out-right">
                        <h4>+8874</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo, deleniti.</p>
                    </div>
                    <div class="number" data-aos="zoom-out-right">
                        <h4>+8874</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo, deleniti.</p>
                    </div>
                    <div class="number" data-aos="zoom-out-right">
                        <h4>+8874</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo, deleniti.</p>
                    </div>
                    <div class="number" data-aos="zoom-out-right">
                        <h4>+8874</h4>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo, deleniti.</p>
                    </div>
                </section>
                <section class="results-text">
                    <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, praesentium.</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui nobis recusandae vitae eaque repellat optio?</p>
                    <a href="#">Sing Up</a>
                </section>
            </div>
        </section>


    <section class="muestras">

        <div>
            <a href="index2.html" class="imgMuestras"><img src="img/compu.png" alt="" width="350px"></a>
            <a href="index2.html" class="linksMuestras">COMPUTADORAS</a>
        </div>

        <div>
            <a href="monitores" class="imgMuestras"> <img src="img/Monitor.b4e0aada.png" alt="" width="350px"></a>
            <a href="monitores" class="linksMuestras">MONITORES</a>
        </div>

        <div>
            <a href="perifericos" class="imgMuestras"> <img src="img/Peripherals.9f53da7d.png" alt="" width="350px"></a>
            <a href="perifericos" class="linksMuestras">PERIFERICOS</a>
        </div>

    </section>



</section>
<?php require 'tempaltes/footer.phtml' ?>