<?php require 'tempaltes/header.phtml' ?>


<form action="newRegistro" method="POST">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input name="email" type="email" class="form-control" id="inputEmail4" placeholder="Email" required>
        </div>
        <div class="form-group col-md-6">
            <label for="inputPassword4">Password</label>
            <input name="contraseña" type="password" class="form-control" id="inputPassword4" placeholder="Password" required>
        </div>
    </div>

    <?php if ($error) : ?>
        <div class='alert alert-danger' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>

    <button type="submit" class="btn btn-primary">Sign in</button>
</form>


<?php require 'tempaltes/footer.phtml' ?>